apiVersion: 1

datasources:
  - name: MySQL-env_monitor
    type: mysql
    access: proxy
    url: localhost:3306
    database: env_monitor
    user: env_user
    secureJsonData:
      password: env_pass123
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      connectionTimeout: 30
    isDefault: true
    editable: true
